<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>OAuth</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<script type="text/javascript" src="/include/js/jquery/jquery-1.11.3.min.js"></script>
		<script type="text/javascript" src="/include/js/bootstrap/bootstrap.min.js"></script>
		<script type="text/javascript" src="/include/js/page/ctrl.js"></script>
	</head>
	<body>
	<?php
		echo $this->pageContent;
	?>
	</body>
</html>